org.gradle.jvmargs=-Xmx1G

#Fabric properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3

#Mod properties
mod_version=1.1.1
maven_group=ru.berdinskiybear.armorhud
mod_id=armor_hud
mod_name=guy's Armor HUD
mod_description=Adds a vanilla-like widget that shows your armor items and a warning if durability is too low. Originally by BerdinskiyBear, then forked by uku made multiloader by AnAwesomGuy.
github=AnAwesomGuy/armor-hud
modrinth_id=AwhZoZsw
curseforge_id=1388138

#TODO UPDATE ME
changelog=some small changes to how the bossbars/effects/subtitles are pushed\
  change the minDurabilityPercentage to be an integer from 1-100\
  other internal code changes

#Dependencies
fabric_loader_version=0.18.4
fabric_api_version=0.116.8+1.21.1
neoforge_version=21.1.219
cloth_config_version=15.0.140
mod_menu_version=11.0.3
